LookupManager/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('django.contrib.auth.urls'), name='login_page'),
    url(r'^documents/', include('csv_app.urls')),
    url(r'^$', RedirectView.as_view(url='account/login', permanent=False),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csv_app/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from csv_app.views import list, detail, object_delete, viewLogs

app_name = 'csv_app'

urlpatterns = [
    #/documents
    url(r'^$', list, name='list'),
    #/documents/<doc_slug>
    url(r'^(?P<document_slug>[-\w\d]+)$', detail, name='detail'),
    #/documents/delete/<doc_id>
    url(r'^delete/(?P<document_id>[0-9]+)$', object_delete, name='delete'),
    #/documents/<doc_slug>/logs
    url(r'^(?P<document_slug>[-\w\d]+)/logs$', viewLogs, name='logs'),
]

templates/documents/detail.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <title>{{ document.docfile.name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>





    <script>
function hide_show() {
    var x = document.getElementById("replace_buttons");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>
</head>
<body>


    <div class="container" style="margin-top: 30px;">
        <h1 class="display-4">{{ document.docfile.name }}</h1>
    </div>


    <div style="margin-top: 50px; margin-left: 80px">


        <form style="float: left; display: inline; width: 25%;">
            <button id="goBack" type="button" class="btn btn-secondary">Go back</button>
            <script type="text/javascript">
            document.getElementById("goBack").onclick = function () {
                window.location.replace("http://localhost:8000/documents/");
            };
            </script>
        </form>


        <form style="float: right; display: inline; width: 42%; " >
            <input type="button" class="btn btn-dark" name="download_JSON" value="Download JSON" onclick="window.location.href='{{ document.json_url }}'" />
        </form>

         <form style="float: right; display: inline; width: 12%;" >
            <input type="button" class="btn btn-primary" value="Download CSV" onclick="window.location.href='{{ document.docfile.url }}'" />
        </form>

        <form style="float: left; display: inline; width: 6%;" >
            <input type="button" class="btn btn-warning" value="Edit" onclick="hide_show()" />
        </form>

        <form style="float: left; display: inline; width: 7%;"  action="{% url 'csv_app:delete' document.id %}" method="post">
            {% csrf_token %}
                <button type="submit" class="btn btn-danger" value="Delete"> Delete </button>
        </form>



        <form style="float: left; display: inline; width: 5%;"  action="{% url 'csv_app:logs' document.slug %}" method="post">
            {% csrf_token %}
                <button type="submit" class="btn btn-info" value="logs"> History </button>
        </form>



</div>

<div id="replace_buttons" style="display:none;margin-top: 100px; margin-left: 450px; ">

    <form action="{% url "csv_app:detail" document.slug %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
    </form>
</div>


</body>





<div class="container" style="margin-top: 155px;">
    <table class="table table-striped">
        <thead>
            <tr>
                {%  for header in header_list %}
                    <th class="text-center"> {{ header }} </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>

            <tr>
                {% for line in csv_content %}
                    <tr>
                    {% for element in line %}
                        <td align="center">{{ element }}</td>
                    {% endfor %}
                    </tr>
                {% endfor %}
        </tbody>

    </table>
</div>
</body>
</html>

templates/documents/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Document List</title>
</head>
<body>

<div>

    <ul>
    {% if all_documents %}
        {% for document in all_documents %}
            <li><a href="/document/{{ document.id }}">{{ document.title }}</a></li>
        {% endfor %}
    {% else %}
        <b>There are no documents to show</b>
    {% endif %}
    </ul>

</div>



<form action="{% url "csv_app:list" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>



</body>
</html>

templates/documents/list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Lookup List</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <script src="http   s://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    </head>

    <body>

    <div class="container" style="margin-top: 30px;">
        <h1 class="display-4" align="center">Lookup List</h1>
    </div>



        <div class="list-group" align="center" style="margin-top: 50px; margin-right: 350px; margin-left: 350px">

            <!-- List of uploaded documents -->
            {% if documents %}

                {% for document in documents %}
                    <a href="{{ document.slug }}" class="list-group-item list-group-item-action">{{ document.title }}</a>
                {% endfor %}

            {# shows the msg that there are no docs    #}
            {% else %}
                <div class="alert alert-warning" style="margin-bottom: 55px;margin-top: 55px">
                    <strong>There are no documents to show!</strong>
                </div>
            {% endif %}


        </div>
        <!-- Upload form. Note enctype attribute! -->
        <form style="margin-left: 350px" action="{% url "csv_app:list" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
    </body>
</html>

templates/documents/logs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <title>Log List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

      <script>
    function goBack() {
        window.history.back()
    }
    </script>

</head>
<body>

    {% if content %}

    <div class="container" style="margin-top: 30px;">
        <h1 class="display-4">Document History</h1>
    </div>
        <button style="margin-top: 20px; margin-left: 90px" onclick="goBack()" type="button" class="btn btn-secondary">Go back</button>

    <div class="container" style="margin-top: 45px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    {%  for header in headers %}
                        <th class="text-center"> {{ header }} </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>

                <tr>
                    {% for line in content %}
                        <tr>
                            {% for element in line %}
                                <td align="center"> {% if not forloop.last %}{{ element }}{%  else %}<form method="get" action={{ element.url }}><button type="submit" class="btn btn-primary">Download</button></form>{% endif %} </td>
                            {% endfor %}


                        </tr>
                    {% endfor %}
            </tbody>

        </table>
    </div>

    {% else %}
        <div class="container" style="margin-top: 30px;">
        <h1 class="display-4">No history available</h1>
        <button style="margin-top: 50px" onclick="goBack()" type="button" class="btn btn-secondary">Go back</button>


    </div>

    {% endif %}

</body>
</html>